name             "authy"
maintainer       "NewMedia Denver"
maintainer_email "devops@newmediadenver.com"
license          "Apache 2.0"
description      "Installs and integrates Authy two factor ssh authentication."
version          "0.1.0"
recipe           "authy::default", "Installs authy."
